# --- Base Avatar Gear ---

- type: startingGear
  id: BitrunnerAvatarGear
  equipment:
    id: BitrunAvatarIDCard

# --- Avatar Loadouts (Netpod) ---

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarPassengerGear
  equipment:
    head: ClothingHeadHatXmasCrown
    neck: ClothingHeadHatFlowerWreath
    outerClothing: ClothingOuterClownPriest
    mask: ClothingMaskClown
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarClownGear
  equipment:
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    gloves: ClothingHandsGlovesFingerlessInsulated
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarMimeGear
  equipment:
    head: ClothingHeadHatBeret
    mask: ClothingMaskMime
    belt: ClothingBeltSuspendersRed
    gloves: ClothingHandsGlovesColorWhite
    jumpsuit: ClothingUniformJumpsuitMime
    shoes: ClothingShoesColorBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarCaptainGear
  equipment:
    neck: ClothingNeckMantleCap
    jumpsuit: ClothingUniformJumpsuitCaptain
    shoes: ClothingShoesColorBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarEngineerGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    gloves: ClothingHandsGlovesFingerlessInsulated
    jumpsuit: ClothingUniformJumpsuitEngineering
    shoes: ClothingShoesBootsWork

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarMedicalDoctorGear
  equipment:
    head: ClothingHeadHatBeretMedic
    gloves: ClothingHandsGlovesNitrile
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    shoes: ClothingShoesColorBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarScientistGear
  equipment:
    head: ClothingHeadHatBeretRND
    gloves: ClothingHandsGlovesLatex
    jumpsuit: ClothingUniformJumpsuitScientist
    shoes: ClothingShoesColorBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarSecurityOfficerGear
  equipment:
    gloves: ClothingHandsGlovesFingerless
    jumpsuit: ClothingUniformJumpsuitSec
    shoes: ClothingShoesBootsCombat

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarCargoTechnicianGear
  equipment:
    head: ClothingHeadHatCargosoft
    gloves: ClothingHandsGlovesFingerless
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesColorBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarSalvageSpecialistGear
  equipment:
    gloves: ClothingHandsGlovesColorBlack
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    neck: ClothingNeckScarfStripedBrown
    shoes: ClothingShoesBootsSalvage

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarShaftMinerGear
  equipment:
    gloves: ClothingHandsGlovesColorBlack
    jumpsuit: ClothingUniformJumpsuitShaftMiner
    neck: ClothingNeckScarfStripedBrown
    shoes: ClothingShoesBootsSalvage

# --- Domain Loadouts ---

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarSecurityOfficerMODGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    outerClothing: ClothingOuterHardsuitCombatOfficer
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsCombat

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarXenonautenGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCamouflage
    head: ClothingHeadHelmetXenonauten
    outerClothing: ClothingOuterArmorXenonautenHeavy
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsCombat
