
# --- ЛОДАУТЫ АВАТАРОВ (Netpod) ---

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarWeeb
  equipment:
    mask: ClothingMaskOniRed
    jumpsuit: ClothingUniformJumpsuitKimono
    shoes: ClothingShoesWizard

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarPG
  equipment:
    head: LPPClothingHeadHatPGPanama
    jumpsuit: LPPClothingUniformJumpsuitPG
    shoes: LPPClothingShoesBootsCombatPG
    neck: LPPClothingNeckMantlePG

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarPGBlack
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    jumpsuit: LPPClothingUniformBlackJumpsuitPG
    gloves: LPPClothingHandsGlovesTacticalFingerless
    shoes: ClothingShoesSwat

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarHorny
  equipment:
    eyes: LPPHypnogogglesPink
    jumpsuit: LPPBikinisBlack
    gloves: ClothingHandsGlovesChemist
    shoes: ClothingShoesBootsLaceup
    breast: LPPSwimsuitplusTightsBodyBra2

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarHornyPriest
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitLacerobe
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesBootsLaceup
    socks: LPPClothingUnderPantyhoseBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarSyndie
  equipment:
    eyes: ClothingEyesGlassesCheapSunglasses
    jumpsuit: ClothingUniformJumpsuitOperative
    gloves: ClothingHandsGlovesChemist
    shoes: ClothingShoesBootsWinterSyndicate

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarGreytide
  equipment:
    mask: ClothingMaskGas
    jumpsuit: ClothingUniformJumpsuitAncient
    gloves: ClothingHandsGlovesFingerlessInsulated
    shoes: ClothingShoesColorBlack

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarSecCamo
  equipment:
    head: LPPClothingHeadSecurityHatCamo
    jumpsuit: LPPClothingUniformJumpsuitSecCamo
    gloves: LPPClothingHandsGlovesTacticalFingerless
    shoes: ClothingShoesSwat
    eyes: ClothingEyesGlassesCheapSunglasses

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarHoS
  equipment:
    head: ClothingHeadHatBeretHoS
    jumpsuit: ClothingUniformJumpsuitHoSAlt
    gloves: LPPClothingHandsGlovesTacticalFingerless
    shoes: ClothingShoesSwat
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingNeckMantleHOSShoulder

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarAISSentinel
  equipment:
    head: ClothingHeadHatAISBeretSentinel
    jumpsuit: ClothingUniformJumpsuitAISArmsman
    gloves: LPPClothingHandsGlovesTacticalFingerless
    shoes: ClothingShoesSwat
    eyes: ClothingEyesGlassesCheapSunglasses

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarUEGCamo
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitCamoUEG
    gloves: LPPClothingHandsGlovesTacticalFingerless
    shoes: LPPClothingShoesBootsUEG
    eyes: ClothingEyesGlassesCheapSunglasses

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarUEGSkitarii
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitOperativeUEG
    gloves: LPPClothingHandsGlovesTacticalFingerless
    shoes: LPPClothingShoesBootsUEG
    eyes: ClothingEyesGlassesCheapSunglasses

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarUEG
  equipment:
    jumpsuit: ClothingUniformJumpsuitUEGFatigueGreen
    gloves: LPPClothingHandsGlovesTacticalFingerless
    shoes: ClothingShoesSwat
    head: ClothingHeadHatUEGArmyGarrison

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarUEGIPC
  equipment:
    jumpsuit: ClothingUniformJumpsuitUEGFatigueIPC
    shoes: ClothingShoesSwat
    outerClothing: ClothingOuterVestTank

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarTacticalMaid
  equipment:
    jumpsuit: ClothingUniformJumpskirtTacticalMaid
    shoes: ClothingShoesSwat
    head: ClothingHeadHatTacticalMaidHeadband

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarCultist
  equipment:
    jumpsuit: ClothingUniformJumpsuitTacticool
    shoes: ClothingShoesCult
    outerClothing: ClothingOuterRobesCult
    head: ClothingHeadHatHoodCulthood
    gloves: ClothingHandsGlovesColorRed
    neck: BedsheetCult

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarRichard
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitSky
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLettermanRed
    head: ClothingHeadHatRichard
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarMerc
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    shoes: ClothingShoesBootsMerc
    mask: ClothingMaskBandMerc
    head: ClothingHeadHatBeretMerc
    gloves: ClothingHandsGlovesMercFingerless

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarTechPriest
  equipment:
    jumpsuit: ClothingUniformJumpsuitRoboticist
    gloves: ClothingHandsGlovesRobohands
    shoes: ClothingShoesCult
    head: ClothingHeadTechPriest
    outerClothing: ClothingOuterRobeTechPriest

# --- ЛОДАУТЫ ДОМЕНОВ ---

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarCombatUEG
  equipment:
    jumpsuit: ClothingUniformJumpsuitUEGFatigueGreen
    shoes: ClothingShoesBootsJackFilled
    outerClothing: ClothingOuterVestWebUEG
    head: ClothingHeadHelmetUEG
    gloves: ClothingHandsMercGlovesCombat
    eyes: LPPClothingEyesGlassesNVG
    mask: ClothingMaskGasSecurity
    belt: ClothingBeltHolster

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarCombatPG
  equipment:
    eyes: LPPClothingEyesGlassesSunglassesPG
    jumpsuit: LPPClothingUniformBlackJumpsuitPG
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
    head: LPPClothingHeadUrbanHelmetPG
    mask: LPPClothingMaskPGWrittenOff
    outerClothing: LPPClothingOuterVestUrbanPG
    belt: ClothingBeltHolster

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarNoirCombat
  equipment:
    eyes: ClothingEyesGlassesNoir
    jumpsuit: ClothingUniformJumpsuitDetectiveGrey
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatFedoraGrey
    outerClothing: ClothingOuterCoatDetectiveDark
    belt: ClothingBeltHolster

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarERTcombat
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
    mask: ClothingMaskGasERT
    belt: ClothingBeltSecurityWebbingFilled

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarUEGSkitariiCombat
  equipment:
    eyes: LPPUEGEyehud
    jumpsuit: LPPClothingUniformJumpsuitOverallsUEG
    gloves: LPPClothingHandsGlovesUEGCombat
    shoes: LPPClothingShoesUEGLegsUnremovable
    mask: LPPClothingMaskUEGExpeditor
    outerClothing: LPPClothingOuterUEGExpeditor
    belt: LPPClothingBeltUEGWebbing

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerAvatarUSSP
  equipment:
    jumpsuit: LPPClothingUniformJumpsuitSoviet
    gloves: ClothingHandsGlovesMercFingerless
    shoes: ClothingShoesBootsJack
    mask: LPPClothingMaskGasSoviet
    outerClothing: LPPClothingOuterArmorSoviet
    belt: LPPClothingBeltSovietWebbing
    head: ClothingHeadHatUshanka
# --- КИБЕРПОЛИЦИЯ ---

- type: startingGear
  parent: BitrunnerAvatarGear
  id: BitrunnerCyberPolice
  equipment:
    eyes: ClothingEyesGlassesBSO
    jumpsuit: ClothingUniformJumpsuitTurtleneckTactick
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCowboyBountyHunter
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterArmorBasic
    belt: ClothingBeltSecurityWebbingFilled
    back: ClothingBackpackSatchel
    pocket1: MagazinePistol
    pocket2: MagazinePistol
    id: BitrunAvatarIDCard

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceEasy
  inhand:
  - WeaponPistolG22
  storage:
    back:
    - MedkitFilled
    - Bola
    - GrenadeFlashBang
    - MagazineBoxPistol
    - Crowbar

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceEasyMelee
  equipment:
    outerClothing: ClothingOuterArmorRiot
    pocket1: CombatKnife
    pocket2: SyringeEphedrine
  inhand:
  - Truncheon
  - TelescopicShield
  storage:
    back:
    - MedkitFilled
    - Bola
    - GrenadeFlashBang
    - MagazineBoxPistol
    - Crowbar

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceEasyMeleeAntilaser
  equipment:
    head: ClothingHeadHelmetHeavyAblative
    pocket1: MagazinePistol
    pocket2: BurnAutoInjector
  inhand:
  - WeaponPistolG22
  storage:
    back:
    - MedkitFilled
    - Bola
    - GrenadeFlashBang
    - MagazineBoxPistol
    - Crowbar

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceMedium
  equipment:
    outerClothing: LPPlothingOuterArmorSwatAlternative
    head: LPPClothingHeadHelmetSwatAlternative
    pocket1: MagazineRifle
    pocket2: MagazineRifle
  inhand:
  - LPPWeaponRifleLemas
  storage:
    back:
    - MedkitFilled
    - Bola
    - GrenadeStinger
    - LPPWeaponEnergyGunPistolDominator
    - Crowbar

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceMediumMelee
  equipment:
    outerClothing: LPPlothingOuterArmorSwat
    head: LPPClothingHeadHelmetSwat
    pocket1: WeaponRevolverFaith
    pocket2: SyringeStimulants
  inhand:
  - CaptainSabre
  - BlueShieldShield
  storage:
    back:
    - MedkitFilled
    - Bola
    - Bola
    - GrenadeStinger
    - Crowbar

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceMediumAntilaser
  equipment:
    outerClothing: ClothingOuterArmorReflective
    head: ClothingHeadHelmetSwat
    pocket1: LPPMagazinePistolPF20lethal
    pocket2: LPPMagazinePistolPF20lethal
  inhand:
  - LPPWeaponPistolPF20
  - LPPKnifeJagdkommando
  storage:
    back:
    - MedkitFilled
    - Bola
    - GrenadeStinger
    - Crowbar

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceHard
  equipment:
    outerClothing: ClothingOuterArmorStandardHeavy
    head: ClothingHeadHelmetHeavyStandard
    mask: ClothingMaskGasSwat
    pocket1: MagazineRifle
    pocket2: MagazineRifle
  inhand:
  - LPPWeaponRifleAek
  storage:
    back:
    - MedkitCombatFilled
    - Bola
    - GrenadeShrapnel
    - JawsOfLife

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceHardMelee
  equipment:
    outerClothing: ClothingOuterArmorRiotHeavy
    head: ClothingHeadHelmetHeavyRiot
    pocket1: StimpackMini
    pocket2: LPPKnifeJagdkommando
  inhand:
  - LPPEnergyAxe
  storage:
    back:
    - MedkitCombatFilled
    - Bola
    - GrenadeShrapnel
    - JawsOfLife

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceHardAntilaser
  equipment:
    outerClothing: ClothingOuterArmorAblativeHeavy
    head: ClothingHeadHelmetSwat
    pocket1: MagazineMagnum
    pocket2: MagazineMagnum
  inhand:
  - WeaponPistolN1984
  - Machete
  storage:
    back:
    - MedkitCombatFilled
    - Bola
    - JawsOfLife
    - MagazineBoxMagnum

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceExtreme
  equipment:
    outerClothing: ClothingOuterArmorHoSHeavy
    head: ClothingHeadHelmetHeavyHoS
    mask: ClothingMaskGasDeathSquad
    shoes: ClothingShoesChameleonNoSlips
    back: LPPClothingBackpackHunter
    pocket1: MagazineRifle
    pocket2: MagazineRifle
  inhand:
  - WeaponRifleM16A4
  storage:
    back:
    - MedkitCombatFilled
    - Bola
    - GrenadeShrapnel
    - JawsOfLife
    - StimpackMini

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceExtremeMelee
  equipment:
    outerClothing: ClothingOuterArmorRiotHeavy
    head: LPPClothingHeadTSFHelmet
    back: LPPClothingBackpackHunter
    pocket1: WeaponPistolG22
    pocket2: AirlossAutoInjector
  inhand:
  - LPPEnergyBroadsword
  - BlueShieldShield
  storage:
    back:
    - MedkitCombatFilled
    - StimkitFilled
    - GrenadeShrapnel
    - JawsOfLife

- type: startingGear
  parent: BitrunnerCyberPolice
  id: BitrunnerCyberPoliceExtremeAntilaser
  equipment:
    outerClothing: LPPClothingOuterArmorErengySyndie
    head: LPPClothingHeadTSFHelmet
    back: LPPClothingBackpackHunter
    pocket1: LPPKnifeJagdkommando
    pocket2: AirlossAutoInjector
  inhand:
  - LPPWeaponRiflepadefame
  storage:
    back:
    - MedkitCombatFilled
    - StimpackMini
    - GrenadeShrapnel
    - JawsOfLife
    - MagazineRifle
    - MagazineRifle
    - MagazineRifle
