using System.Linq;
using Content.Client.Materials;
using Content.Client.Power.Components;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Medical.Disease.Systems;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._FarHorizons.Medical.Disease.UI;

[GenerateTypedNameReferences]
public sealed partial class VaccinatorMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public event Action? CreateVaccineAction;
    private readonly MaterialStorageSystem _materialStorage;
    private readonly SharedContainerSystem _container;
    private readonly SharedSolutionContainerSystem _solutionContainer;
    private static readonly string _vaccine = "Vaccine";
    private Dictionary<DiseaseData, float> _immunity = [];
    public EntityUid Entity;
    public VaccinatorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _materialStorage = _entityManager.System<MaterialStorageSystem>();
        _container = _entityManager.System<SharedContainerSystem>();
        _solutionContainer = _entityManager.System<SharedSolutionContainerSystem>();

        CreateVaccineButton.OnPressed += _ => CreateVaccineAction?.Invoke();
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;
        MaterialsList.SetOwner(Entity);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateImmunities();
        CheckIfCraftable();
    }

    public void UpdateImmunities()
    {
        if(!_container.TryGetContainer(Entity, "sample", out var sampleContainer))
        {
            NoImmunityDataText.Visible = true;
            return;
        }

        var vial = sampleContainer.ContainedEntities.FirstOrNull();
        if (vial == null)
        {
            NoImmunityDataText.Visible = true;
            return;
        }

        Dictionary<string, (DiseaseData disease, float value)> immunityByName = [];

        if(!_solutionContainer.TryGetSolution(vial.Value, "drink", out var solution))
        {
            NoImmunityDataText.Visible = true;
            return;
        }

        var immunities = solution.Value.Comp.Solution;
        foreach(var immunity in immunities)
        {
            if(immunity.Reagent.Data == null)
                continue;
            var diseaseData = immunity.Reagent.Data.OfType<DiseaseReagentData>().FirstOrDefault();
            if (diseaseData == null)
                continue;

            foreach (var (disease, value) in diseaseData.Immunity)
            {
                string diseaseKey = disease.Name;

                if (!immunityByName.TryGetValue(diseaseKey, out var existing) || value > existing.value)
                    immunityByName[diseaseKey] = (disease, value);
            }
        }

        // Convert back to original dictionary format
        Dictionary<DiseaseData, float> newImmunity = immunityByName.Values.ToDictionary(x => x.disease, x => x.value);

        if(newImmunity.Count == _immunity.Count &&
        newImmunity.All(kvp => _immunity.TryGetValue(kvp.Key, out var v) && v == kvp.Value))
        {
            NoImmunityDataText.Visible = _immunity.Count == 0;
            return;
        }

        _immunity = newImmunity;
        ImmunityPanel.DisposeAllChildren();
        NoImmunityDataText.Visible = false;

        foreach(var immunity in _immunity)
        {
            var Row = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal
            };

            var ImmunityName = new Label()
            {
                Text = Loc.GetString(immunity.Key.Name),
                Margin = new Thickness(10, 10, 0, -5),
                SetWidth = 130
            };
            var ImmunityStrength = new Label()
            {
                Text = $"{Math.Round(immunity.Value*100)}%",
                Margin = new Thickness(0, 10, 0, -5)
            };
            Row.AddChild(ImmunityName);
            Row.AddChild(ImmunityStrength);
            ImmunityPanel.AddChild(Row);
        }
    }
    public void CheckIfCraftable()
    {
        if (!_prototypeManager.TryIndex<LatheRecipePrototype>(_vaccine, out var recipe))
            return;

        bool canCraft = true;
        foreach (var (id, amount) in recipe.Materials)
        {
            if (!_prototypeManager.Resolve(id, out var material))
                continue;
            var sheetVolume = _materialStorage.GetSheetVolume(material);
            var sheets = amount / (float) sheetVolume;

            var availableAmount = _materialStorage.GetMaterialAmount(Entity, id);
            var missingAmount = Math.Max(0, amount - availableAmount);
            var missingSheets = missingAmount / (float) sheetVolume;
            if(missingSheets > 0)
            {
                canCraft = false;
                break;
            }
        }
        if(_entityManager.TryGetComponent<ApcPowerReceiverComponent>(Entity, out var powerComp) && !powerComp.Powered)
        {
            CreateVaccineButton.ToolTip = "No Power";
            CreateVaccineButton.Disabled = true;
            return;
        }

        if(NoImmunityDataText.Visible)
        {
            CreateVaccineButton.ToolTip = "No Antibodies Detected.";
            CreateVaccineButton.Disabled = true;
            return;
        }

        CreateVaccineButton.Disabled = !canCraft;

        if (!canCraft)
            CreateVaccineButton.ToolTip = "Insufficient materials. Vaccines requires 1 steel 0.5 plastic.";
        else
            CreateVaccineButton.ToolTip = "Create vaccine";
    }
}
