using Content.Shared._Orion.Bitrunning;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Bitrunning.UI.Netpod;

[GenerateTypedNameReferences]
public sealed partial class NetpodWindow : DefaultWindow
{
    public Action<string>? OnSelectLoadout;

    private NetpodBoundUiState? _state;
    private bool _suppressSelectionEvents;

    public NetpodWindow()
    {
        RobustXamlLoader.Load(this);
        Search.OnTextChanged += _ => Rebuild();
        OutfitList.OnItemSelected += OnItemSelected;
    }

    public void UpdateState(NetpodBoundUiState state)
    {
        _state = state;
        Rebuild();
    }

    private void Rebuild()
    {
        _suppressSelectionEvents = true;
        OutfitList.Clear();

        if (_state == null)
        {
            _suppressSelectionEvents = false;
            return;
        }

        var filter = Search.Text.Trim();
        foreach (var loadout in _state.Loadouts)
        {
            if (!string.IsNullOrEmpty(filter) &&
                loadout.Name.IndexOf(filter, StringComparison.OrdinalIgnoreCase) < 0 &&
                loadout.Id.IndexOf(filter, StringComparison.OrdinalIgnoreCase) < 0)
                continue;

            var item = new ItemList.Item(OutfitList)
            {
                Text = loadout.Name,
                Metadata = loadout.Id,
            };

            OutfitList.Add(item);

            if (_state.SelectedLoadout == loadout.Id)
                OutfitList[^1].Selected = true;
        }

        _suppressSelectionEvents = false;
    }

    private void OnItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (_suppressSelectionEvents)
            return;

        if (args.ItemList[args.ItemIndex].Metadata is not string id)
            return;

        OnSelectLoadout?.Invoke(id);
    }
}
