# За баланс хз, вроде достаточно дорогие
- type: latheRecipe
  id: LPPBorgModuleSecurityWeapon
  result: LPPBorgModuleSecurityWeapon
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  id: LPPBorgModuleSecurityLaserCarbine
  result: LPPBorgModuleSecurityLaserCarbine
  materials:
    Steel: 3000
    Glass: 1000
    Plastic: 500

- type: latheRecipe
  id: LPPBorgModuleSecurityCriminologist
  result: LPPBorgModuleSecurityCriminologist
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 800

- type: latheRecipe
  id: LPPC4Low
  result: LPPC4Low
  completetime: 10
  materials:
    Plastic: 375
    Plasma: 375

# Hardsuits

# Base cost: Plastic: 1000

# Every hardsuit what has helmet with window must have += Glass: 200

# If hardsuit has no resist or buffs => Plastic: 1000

# If hardsuit has speed buffs += Plastic: 1000

# If hardsuit dosnt have buffs but has resist -= Plastic: 1000 and += Steel: 500

# If hardsuit dosnt have resist but has speed debuff += 1 Plastic for every 10%

# If hardsuit dosnt have speed buff/debuff but has resists += Plastic: 1000

# Every Blunt/Pierce/Slash damage 10% += 1 Steel until resist is higher than 40%
# Every 10% Blunt/Pierce/Slash damage higher than 40% += 2 Plasteel

# Every Radiation damage 10% += 1 Plasma until resist is higher than 40%
# Every 10% Radiation damage higher than 40% += 2 Plasma

# Every 10% speed debuff += 1 Plasteel

# Every Fire damage 10% += 1 Gold

# Every Explosive damage 10% += 1 Silver

# Every High Temp damage 10% += 1 Gold

# Every Acid damage 10% += 1 Silver

# Every Electical damage 10% += 1 Steel

# Every Stamina damage 10% += 2 Plasteel

- type: latheRecipe
  id: LPPClothingHeadHelmetEVALarge
  result: ClothingHeadHelmetEVALarge
  parent: LPPLatheRecipe15Sec
  materials:
    Glass: 200
    Plastic: 1000

- type: latheRecipe
  id: LPPClothingOuterHardsuitEVAPrisoner
  result: ClothingOuterHardsuitEVAPrisoner
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 300
    Plastic: 1000

- type: latheRecipe
  id: LPPClothingOuterHardsuitCombatOfficer
  result: ClothingOuterHardsuitCombatOfficer
  parent: LPPLatheRecipe15Sec
  materials:
    Steel: 1950
    Plasma: 1350
    Silver: 750
    Gold: 350
    Plasteel: 1050
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitSecurity
  result: ClothingOuterHardsuitSecurity
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 250
    Steel: 2000
    Gold: 300
    Silver: 900
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitCombatMedical
  result: ClothingOuterHardsuitCombatMedical
  parent: LPPLatheRecipe15Sec
  materials:
    Steel: 2000
    Plasma: 200
    Silver: 600
    Gold: 350
    Plasteel: 950
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitCombatRiot
  result: ClothingOuterHardsuitCombatRiot
  parent: LPPLatheRecipe15Sec
  materials:
    Steel: 2750
    Plasteel: 2200
    Plasma: 300
    Silver: 900
    Gold: 950
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitSecurityPilot
  result: ClothingOuterHardsuitSecurityPilot
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 250
    Steel: 2000
    Gold: 300
    Silver: 900
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitSecurityEng
  result: LPPClothingOuterHardsuitSecurityEng
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 275
    Steel: 1500
    Silver: 200
    Gold: 950
    Plasma: 950
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitBrigmedic
  result: ClothingOuterHardsuitBrigmedic
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 150
    Steel: 1650
    Glass: 200
    Gold: 50
    Plasma: 100
    Silver: 100

- type: latheRecipe
  id: LPPClothingOuterHardsuitWarden
  result: ClothingOuterHardsuitWarden
  parent: LPPLatheRecipe15Sec
  materials:
    Steel: 2000
    Plasteel: 800
    Gold: 300
    Silver: 900
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitLuxury
  result: ClothingOuterHardsuitLuxury
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 100
    Steel: 1050
    Gold: 200
    Plasma: 1700
    Silver: 300
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitRd
  result: LPPClothingOuterHardsuitRd
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 250
    Steel: 1450
    Gold: 800
    Plasma: 2500
    Silver: 1700
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitMedical
  result: ClothingOuterHardsuitMedical
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 50
    Steel: 750
    Gold: 100
    Silver: 900
    Glass: 200
    Plasma: 1100

- type: latheRecipe
  id: LPPClothingOuterHardsuitEngineeringWhite
  result: ClothingOuterHardsuitEngineeringWhite
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 200
    Steel: 1350
    Gold: 1500
    Plasma: 2700
    Silver: 1300
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitSecurityRed
  result: ClothingOuterHardsuitSecurityRed
  parent: LPPLatheRecipe15Sec
  materials:
    Steel: 2000
    Plasteel: 600
    Plasma: 600
    Silver: 900
    Glass: 200
    Gold: 100

- type: latheRecipe
  id: LPPClothingOuterHardsuitMaxim
  result: ClothingOuterHardsuitMaxim
  parent: LPPLatheRecipe15Sec
  materials:
    Steel: 1700
    Plasteel: 200
    Gold: 150
    Plasma: 1400
    Silver: 800
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitCap
  result: ClothingOuterHardsuitCap
  parent: LPPLatheRecipe15Sec
  materials:
    Plasteel: 200
    Steel: 1550
    Gold: 600
    Plasma: 1700
    Silver: 900
    Glass: 200

- type: latheRecipe
  id: LPPClothingOuterHardsuitCombatAlternative
  result: LPPClothingOuterHardsuitCombatAlternative
  parent: LPPLatheRecipe15Sec
  materials:
    Steel: 2000
    Plasteel: 600
    Plasma: 600
    Silver: 900
    Glass: 200
    Gold: 100
# Weapons

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: LPPWeaponLauncherHydrozoa
  result: LPPWeaponLauncherHydrozoa
  materials:
    Steel: 1250
    Plastic: 750
    Gold: 350

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: LPPWeaponRifleM14
  result: LPPWeaponRifleM14
  materials:
    Steel: 2500
    Plastic: 250

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: LPPGrenadeEMP
  result: GrenadeEMP
  materials:
    Plastic: 500
    Steel: 500

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: LPPGrenadeBaton
  result: GrenadeBaton
  materials:
    Plastic: 500
    Steel: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: LPPMagazineShotgunLeverRifle
  result: MagazineShotgunLeverRifle
  materials:
    Steel: 475

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: LPPWeaponPF20kit
  result: LPPCBoxCardboardArmoryPF20
  materials:
    Steel: 4000
    Plastic: 1250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: LPPMagazinePistolPF20lethal
  result: LPPMagazinePistolPF20lethal
  materials:
    Steel: 350

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: LPPMagazineLightSniper
  result: LPPMagazineLightSniper
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: LPPWeaponSniperScout
  result: LPPWeaponSniperScout
  materials:
    Steel: 2000
    Plastic: 500
    Glass: 1000

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponStarflareSMG
  result: WeaponStarflareSMG
  materials:
    Steel: 1800
    Glass: 800
    Plastic: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PowerCellStarflarePrinted
  result: PowerCellStarflarePrinted
  materials:
    Steel: 600
    Glass: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSpecial
  result: MagazinePistolSpecial
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderSpecial
  result: SpeedLoaderSpecial
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSpecialPractice
  result: MagazinePistolSpecialPractice
  materials:
    Steel: 175

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderSpecialPractice
  result: SpeedLoaderSpecialPractice
  materials:
    Steel: 175

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderSpecialRubber
  result: SpeedLoaderSpecialRubber
  materials:
    Steel: 150
    Plastic: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSpecialRubber
  result: MagazinePistolSpecialRubber
  materials:
    Steel: 150
    Plastic: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderSpecialUranium
  result: SpeedLoaderSpecialUranium
  materials:
    Plastic: 150
    Uranium: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxSpecial
  result: MagazineBoxSpecial
  materials:
    Steel: 450

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxSpecialPractice
  result: MagazineBoxSpecialPractice
  materials:
    Steel: 275

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxSpecialRubber
  result: MagazineBoxSpecialRubber
  materials:
    Steel: 275
    Plastic: 125

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxSpecialUranium
  result: MagazineBoxSpecialUranium
  materials:
    Plastic: 275
    Uranium: 140

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxSpecialIncendiary
  result: MagazineBoxSpecialIncendiary
  materials:
    Steel: 125
    Plastic: 275

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: LPPMagazinePistolPF20Practice
  result: LPPMagazinePistolPF20Practice
  materials:
    Steel: 125

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: LPPMagazinePistolPF20Incendiary
  result: LPPMagazinePistolPF20Incendiary
  materials:
    Steel: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: LPPMagazinePistolPF20Uranium
  result: LPPMagazinePistolPF20Uranium
  materials:
    Steel: 75
    Uranium: 100

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponAutoDisabler
  result: WeaponAutoDisabler
  materials:
    Steel: 900
    Glass: 300
    Plastic: 300

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponPocketDisabler
  result: WeaponPocketDisabler
  materials:
    Steel: 500
    Glass: 100
    Plastic: 100

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponStunProjector
  result: WeaponStunProjector
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisablerCarbine
  result: WeaponDisablerCarbine
  materials:
    Steel: 1000
    Glass: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponDisablerShotgun
  result: WeaponDisablerShotgun
  materials:
    Steel: 2000
    Glass: 1000
    Plastic: 1000

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: LPPWeaponEnergyGunPistolDominator
  result: LPPWeaponEnergyGunPistolDominator
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Plasma: 750

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponEnergyGunPistol
  result: WeaponEnergyGunPistol
  materials:
    Steel: 1750
    Glass: 250
    Plastic: 250
    Gold: 500
    Silver: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: LPPWeaponRiflepadefame
  result: LPPWeaponRiflepadefame
  materials:
    Steel: 3000
    Glass: 250
    Plastic: 1000

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponEnergyGun
  result: WeaponEnergyGun
  materials:
    Steel: 2000
    Glass: 500
    Plastic: 500
    Gold: 100

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponGunLaserCarbineAutomatic
  result: WeaponGunLaserCarbineAutomatic
  materials:
    Steel: 4000
    Glass: 2000
    Plastic: 1500
    Gold: 1000
    Silver: 1000
