using System.Globalization;
using System.Linq;
using System.Numerics;
using Content.Shared._Orion.Bitrunning;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Bitrunning.UI;

[GenerateTypedNameReferences]
public sealed partial class QuantumConsoleWindow : DefaultWindow
{
    public Action<string>? OnLoadDomain;
    public Action<bool>? OnBroadcastToggle;
    public Action? OnRandomDomain;
    public Action? OnStopDomain;
    public Action? OnRefresh;

    private QuantumConsoleBoundUiState? _lastState;
    private BitrunningDifficulty? _selectedDifficulty;
    private string? _expandedDomainId;
    private bool _updatingToggle;
    private readonly Dictionary<string, DomainRowWidgets> _domainRows = new();

    public QuantumConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ApplyStaticStyling();
        ConfigureDifficultyTabs();

        RandomButton.OnPressed += _ => OnRandomDomain?.Invoke();
        StopButton.OnPressed += _ => OnStopDomain?.Invoke();
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        BroadcastToggle.OnToggled += args =>
        {
            if (_updatingToggle)
                return;

            OnBroadcastToggle?.Invoke(args.Pressed);
        };
    }

    public void UpdateState(QuantumConsoleBoundUiState state)
    {
        _lastState = state;

        if (!state.ExtremeDifficultyUnlocked && _selectedDifficulty == BitrunningDifficulty.Extreme)
            _selectedDifficulty = null;

        DifficultyExtreme.Visible = state.ExtremeDifficultyUnlocked;

        ConnectedValue.Text = state.Connected
            ? Loc.GetString("bitrunning-console-connected")
            : Loc.GetString("bitrunning-console-disconnected");
        ConnectedValue.FontColorOverride = state.Connected ? Color.SpringGreen : Color.IndianRed;

        PointsValue.Text = Loc.GetString("bitrunning-ui-server-points-badge", ("points", state.ServerPoints.ToString(CultureInfo.InvariantCulture)));
        ClientsHeader.Text = Loc.GetString("bitrunning-ui-clients-header-count", ("count", state.Occupants.ToString(CultureInfo.InvariantCulture)));
        ScannerValue.Text = Loc.GetString("bitrunning-ui-scanner-inline", ("scanner", state.ConnectedPods.ToString(CultureInfo.InvariantCulture)));
        StateValue.Text = GetStateText(state);

        CurrentDomainValue.Text = ResolveCurrentDomainName(state.CurrentDomain, state.Domains);
        CurrentDomainValue.FontColorOverride = state.CurrentDomain == null ? Color.Silver : Color.AliceBlue;

        _updatingToggle = true;
        BroadcastToggle.Pressed = state.Broadcast;
        _updatingToggle = false;

        StopButton.Disabled = !state.Connected || state.State != BitrunningServerState.Running;
        RandomButton.Disabled = !state.Connected || state.State != BitrunningServerState.Ready;

        UpdateCooldown(state);
        RebuildDomainList(state);
        RebuildClientList(state);
        UpdateDifficultySelectionVisuals();
    }

    private static string GetStateText(QuantumConsoleBoundUiState state)
    {
        var text = state.State switch
        {
            BitrunningServerState.Ready => Loc.GetString("bitrunning-ui-state-ready"),
            BitrunningServerState.Running => Loc.GetString("bitrunning-ui-state-running"),
            BitrunningServerState.CoolingDown => Loc.GetString("bitrunning-ui-state-cooling"),
            _ => state.State.ToString(),
        };

        if (state.State != BitrunningServerState.CoolingDown)
            return Loc.GetString("bitrunning-ui-server-state", ("state", text));

        var remaining = TimeSpan.FromSeconds(state.CooldownRemainingSeconds);
        var formatted = $"{remaining.Minutes:D2}:{remaining.Seconds:D2}";
        text = Loc.GetString("bitrunning-ui-state-cooling-time", ("time", formatted));

        return Loc.GetString("bitrunning-ui-server-state", ("state", text));
    }

    private void UpdateCooldown(QuantumConsoleBoundUiState state)
    {
        if (state.State != BitrunningServerState.CoolingDown || state.CooldownTotalSeconds <= 0)
        {
            CooldownLabel.Text = Loc.GetString("bitrunning-ui-cooldown-ready");
            CooldownBar.Value = 1f;
            CooldownBar.ModulateSelfOverride = Color.FromHex("#3fa34d");
            return;
        }

        var progress = 1f - Math.Clamp(state.CooldownRemainingSeconds / state.CooldownTotalSeconds, 0f, 1f);
        CooldownLabel.Text = Loc.GetString("bitrunning-ui-cooldown-active");
        CooldownBar.Value = progress;
        CooldownBar.ModulateSelfOverride = Color.FromHex("#d19b2a");
    }

    private void RebuildDomainList(QuantumConsoleBoundUiState state)
    {
        var seenDomains = new HashSet<string>();

        foreach (var domain in state.Domains)
        {
            seenDomains.Add(domain.Id);

            if (!_domainRows.TryGetValue(domain.Id, out var row))
            {
                row = CreateDomainRow(domain.Id);
                _domainRows[domain.Id] = row;
            }

            UpdateDomainRow(row, domain, state);

            if (_selectedDifficulty != null && domain.Difficulty != _selectedDifficulty.Value)
            {
                if (row.Holder.Parent == DomainList)
                    DomainList.RemoveChild(row.Holder);

                continue;
            }

            if (row.Holder.Parent != DomainList)
                DomainList.AddChild(row.Holder);
        }

        foreach (var (domainId, row) in _domainRows.ToArray())
        {
            if (seenDomains.Contains(domainId))
                continue;

            if (row.Holder.Parent == DomainList)
                DomainList.RemoveChild(row.Holder);

            _domainRows.Remove(domainId);
        }

        if (_expandedDomainId != null && state.Domains.All(d => d.Id != _expandedDomainId))
            _expandedDomainId = null;
    }

    private void RebuildClientList(QuantumConsoleBoundUiState state)
    {
        ClientList.RemoveAllChildren();

        if (state.ConnectedAvatars.Count == 0)
        {
            ClientList.AddChild(new Label
            {
                Text = Loc.GetString("bitrunning-ui-no-clients"),
                FontColorOverride = Color.FromHex("#8d8d8d"),
            });
            return;
        }

        foreach (var client in state.ConnectedAvatars)
        {
            ClientList.AddChild(CreateClientRow(client));
        }
    }

    private DomainRowWidgets CreateDomainRow(string domainId)
    {
        var holder = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 1,
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            MinSize = new Vector2(0f, 23f),
        };

        var domainButton = new Button
        {
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left,
            MinSize = new Vector2(0f, 23f),
        };
        domainButton.OnPressed += _ =>
        {
            _expandedDomainId = _expandedDomainId == domainId ? null : domainId;

            if (_lastState != null)
                RebuildDomainList(_lastState);
        };

        var deployButton = new Button
        {
            MinSize = new Vector2(90f, 23f),
        };
        deployButton.OnPressed += _ => OnLoadDomain?.Invoke(domainId);

        row.AddChild(domainButton);
        row.AddChild(deployButton);

        holder.AddChild(row);

        var detailsRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            Margin = new Thickness(8, 0, 4, 3),
            HorizontalExpand = true,
        };

        var description = new RichTextLabel
        {
            MaxWidth = 360,
            HorizontalExpand = true,
        };

        var costLabel = new Label
        {
            HorizontalAlignment = HAlignment.Right,
            MinSize = new Vector2(70f, 0f),
            MouseFilter = MouseFilterMode.Stop,
        };

        detailsRow.AddChild(description);
        detailsRow.AddChild(costLabel);
        holder.AddChild(detailsRow);

        return new DomainRowWidgets(holder, domainButton, deployButton, detailsRow, description, costLabel);
    }

    private void UpdateDomainRow(DomainRowWidgets row, BitrunningDomainListing domain, QuantumConsoleBoundUiState state)
    {
        var serverReady = state.State == BitrunningServerState.Ready;
        var enoughServerPoints = state.ServerPoints >= domain.Cost;
        var canDeploy = state.Connected && serverReady && enoughServerPoints;
        var isCurrent = state.CurrentDomain != null && state.CurrentDomain.Equals(domain.Id, StringComparison.Ordinal);
        var expanded = _expandedDomainId == domain.Id;

        row.DomainButton.Text = expanded
            ? $"▾ {domain.Name}"
            : $"▸ {domain.Name}";
        row.DomainButton.ModulateSelfOverride = GetDifficultyColor(domain.Difficulty);

        row.DeployButton.Text = isCurrent && state.State == BitrunningServerState.Running
            ? Loc.GetString("bitrunning-ui-button-deployed")
            : Loc.GetString("bitrunning-ui-button-deploy");
        row.DeployButton.Disabled = !canDeploy;
        row.DeployButton.ToolTip = canDeploy
            ? null
            : !serverReady
                ? Loc.GetString("bitrunning-ui-cannot-deploy-server-busy")
                : Loc.GetString("bitrunning-ui-cannot-deploy-not-enough-server-points");

        row.Description.SetMessage(domain.Description);
        row.CostLabel.Text = Loc.GetString("bitrunning-ui-domain-cost", ("cost", domain.Cost.ToString(CultureInfo.InvariantCulture)));
        row.CostLabel.ToolTip = Loc.GetString("bitrunning-ui-domain-cost-tooltip");
        row.DetailsRow.Visible = expanded;
    }

    private static Control CreateClientRow(BitrunningOccupantListing client)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 5,
            MinSize = new Vector2(0f, 22f),
        };

        row.AddChild(new Label
        {
            Text = client.Name,
            HorizontalExpand = true,
        });

        var icons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 3,
        };

        icons.AddChild(CreateIconBadge("•", "bitrunning-ui-client-icon-linked"));
        icons.AddChild(CreateIconBadge("◔", "bitrunning-ui-client-icon-signal"));
        icons.AddChild(CreateIconBadge("◕", "bitrunning-ui-client-icon-active"));

        if (client.NoHit)
            icons.AddChild(CreateIconBadge("✓", "bitrunning-ui-client-icon-nohit"));

        row.AddChild(icons);
        row.AddChild(CreatePercentBadge(client.NoHit
            ? Loc.GetString("bitrunning-ui-client-percent-perfect")
            : Loc.GetString("bitrunning-ui-client-percent-online")));

        return row;
    }

    private static Control CreateIconBadge(string icon, string tooltipKey)
    {
        var tooltip = Loc.GetString(tooltipKey);
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#1f2537"),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 0,
                ContentMarginBottomOverride = 0,
            },
            ToolTip = tooltip,
            MouseFilter = MouseFilterMode.Stop,
        };

        panel.AddChild(new Label
        {
            Text = icon,
            FontColorOverride = Color.Silver,
            ToolTip = tooltip,
            MouseFilter = MouseFilterMode.Stop,
        });

        return panel;
    }

    private static Control CreatePercentBadge(string text)
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#4e9b23"),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 1,
                ContentMarginBottomOverride = 1,
            },
            MinSize = new Vector2(78f, 0f),
        };

        panel.AddChild(new Label
        {
            Text = text,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.White,
        });

        return panel;
    }

    private static string ResolveCurrentDomainName(string? currentDomainId, IReadOnlyList<BitrunningDomainListing> domains)
    {
        if (currentDomainId == null)
            return Loc.GetString("bitrunning-ui-current-domain-none");

        var domainNames = new Dictionary<string, string>();
        foreach (var domain in domains)
        {
            domainNames[domain.Id] = domain.Name;
        }

        return domainNames.GetValueOrDefault(currentDomainId, currentDomainId);
    }

    private void ConfigureDifficultyTabs()
    {
        DifficultyPeaceful.Text = Loc.GetString("bitrunning-ui-difficulty-peaceful");
        DifficultyEasy.Text = Loc.GetString("bitrunning-ui-difficulty-easy");
        DifficultyMedium.Text = Loc.GetString("bitrunning-ui-difficulty-medium");
        DifficultyHard.Text = Loc.GetString("bitrunning-ui-difficulty-hard-skull");
        DifficultyExtreme.Text = Loc.GetString("bitrunning-ui-difficulty-extreme");

        ConfigureDifficultyButton(DifficultyPeaceful, BitrunningDifficulty.Peaceful, DifficultyColor.Peaceful);
        ConfigureDifficultyButton(DifficultyEasy, BitrunningDifficulty.Easy, DifficultyColor.Easy);
        ConfigureDifficultyButton(DifficultyMedium, BitrunningDifficulty.Medium, DifficultyColor.Medium);
        ConfigureDifficultyButton(DifficultyHard, BitrunningDifficulty.Hard, DifficultyColor.Hard);
        ConfigureDifficultyButton(DifficultyExtreme, BitrunningDifficulty.Extreme, DifficultyColor.Hard);
    }

    private void ConfigureDifficultyButton(Button button, BitrunningDifficulty difficulty, Color color)
    {
        button.ModulateSelfOverride = color;
        button.OnPressed += _ =>
        {
            _selectedDifficulty = _selectedDifficulty == difficulty ? null : difficulty;

            if (_lastState != null)
                RebuildDomainList(_lastState);

            UpdateDifficultySelectionVisuals();
        };
    }

    private void UpdateDifficultySelectionVisuals()
    {
        ApplyDifficultyState(DifficultyPeaceful, BitrunningDifficulty.Peaceful);
        ApplyDifficultyState(DifficultyEasy, BitrunningDifficulty.Easy);
        ApplyDifficultyState(DifficultyMedium, BitrunningDifficulty.Medium);
        ApplyDifficultyState(DifficultyHard, BitrunningDifficulty.Hard);
        ApplyDifficultyState(DifficultyExtreme, BitrunningDifficulty.Extreme);
    }

    private void ApplyDifficultyState(Button button, BitrunningDifficulty? difficulty)
    {
        var baseText = difficulty switch
        {
            BitrunningDifficulty.Peaceful => Loc.GetString("bitrunning-ui-difficulty-peaceful"),
            BitrunningDifficulty.Easy => Loc.GetString("bitrunning-ui-difficulty-easy"),
            BitrunningDifficulty.Medium => Loc.GetString("bitrunning-ui-difficulty-medium"),
            BitrunningDifficulty.Hard => Loc.GetString("bitrunning-ui-difficulty-hard-skull"),
            BitrunningDifficulty.Extreme => Loc.GetString("bitrunning-ui-difficulty-extreme"),
            _ => throw new NotImplementedException(),
        };

        var selected = _selectedDifficulty == difficulty;
        button.Text = selected
            ? Loc.GetString("bitrunning-ui-difficulty-selected", ("name", baseText))
            : baseText;
    }

    private void ApplyStaticStyling()
    {
        DomainsPanel.PanelOverride = CreatePanelStyle("#111318");
        ClientsPanel.PanelOverride = CreatePanelStyle("#111318");
        ActiveDomainPanel.PanelOverride = CreatePanelStyle("#111318");
        ActiveDomainBadge.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#225b99"),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 2,
            ContentMarginBottomOverride = 2,
        };
        PointsBadge.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1e243a"),
            ContentMarginLeftOverride = 2,
            ContentMarginRightOverride = 2,
            ContentMarginTopOverride = 1,
            ContentMarginBottomOverride = 1,
        };
        PointsValue.FontColorOverride = Color.HotPink;
        VirtualDomainsHeader.FontColorOverride = Color.White;
        ClientsHeader.FontColorOverride = Color.White;
        MetaRow.Visible = true;
    }

    private static StyleBoxFlat CreatePanelStyle(string hex)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(hex),
            BorderColor = Color.FromHex("#2a2d36"),
            BorderThickness = new Thickness(1),
        };
    }

    private static Color GetDifficultyColor(BitrunningDifficulty difficulty)
    {
        return difficulty switch
        {
            BitrunningDifficulty.Peaceful => DifficultyColor.Peaceful,
            BitrunningDifficulty.Easy => DifficultyColor.Easy,
            BitrunningDifficulty.Medium => DifficultyColor.Medium,
            BitrunningDifficulty.Hard or BitrunningDifficulty.Extreme => DifficultyColor.Hard,
            _ => Color.FromHex("#B03030"),
        };
    }

    private static class DifficultyColor
    {
        public static readonly Color Peaceful = Color.FromHex("#2ca85e");
        public static readonly Color Easy = Color.FromHex("#d4b300");
        public static readonly Color Medium = Color.FromHex("#d78500");
        public static readonly Color Hard = Color.FromHex("#d12a2a");
    }

    private sealed class DomainRowWidgets
    {
        public BoxContainer Holder { get; }
        public Button DomainButton { get; }
        public Button DeployButton { get; }
        public BoxContainer DetailsRow { get; }
        public RichTextLabel Description { get; }
        public Label CostLabel { get; }

        public DomainRowWidgets(BoxContainer holder, Button domainButton, Button deployButton, BoxContainer detailsRow, RichTextLabel description, Label costLabel)
        {
            Holder = holder;
            DomainButton = domainButton;
            DeployButton = deployButton;
            DetailsRow = detailsRow;
            Description = description;
            CostLabel = costLabel;
        }
    }
}
