using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Orion.Bitrunning.UI.Disk;

[GenerateTypedNameReferences]
public sealed partial class BitrunningDiskWindow : DefaultWindow
{
    private readonly ILocalizationManager _loc;
    public event Action<string>? OnSelected;

    public BitrunningDiskWindow()
    {
        RobustXamlLoader.Load(this);

        _loc = IoCManager.Resolve<ILocalizationManager>();
    }

    public void SetState(List<string> options, string? selectedOption)
    {
        OptionsContainer.RemoveAllChildren();

        if (selectedOption != null)
        {
            var selectedLabel = new Label
            {
                Text = _loc.GetString("bitrunning-disk-ui-selected", ("option", LocalizeOption(selectedOption))),
            };
            OptionsContainer.AddChild(selectedLabel);
            return;
        }

        foreach (var option in options)
        {
            var button = new Button
            {
                Text = LocalizeOption(option),
            };

            button.OnPressed += _ => OnSelected?.Invoke(option);
            OptionsContainer.AddChild(button);
        }
    }

    private string LocalizeOption(string optionKey)
    {
        return _loc.TryGetString(optionKey, out var localizedOption)
            ? localizedOption
            : optionKey;
    }
}
