## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  - MagazineBoxLightRiflePractice
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBoxRiflePractice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - MagazineLightRiflePractice
  - MagazineRiflePractice
  - MagazinePistolPractice
  - SpeedLoaderMagnumPractice
  - MagazinePistolSubMachineGunPractice
  - WeaponFlareGunSecurity

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - MagazineBoxLightRifle
  - MagazineBoxMagnum
  - MagazineBoxPistol
  - MagazineBoxRifle
  - MagazineLightRifle
  - MagazineLightRifleEmpty
  - MagazinePistol
  - MagazinePistolEmpty
  - MagazinePistolSubMachineGun
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazineRifle
  - MagazineRifleEmpty
  - SpeedLoaderMagnum
  - SpeedLoaderMagnumEmpty
  # LP Edit Start
  - LPPMagazineShotgunLeverRifle
  - LPPMagazinePistolPF20lethal
  - LPPMagazineLightSniper
  - MagazinePistolSpecial
  - SpeedLoaderSpecial
  - MagazinePistolSpecialPractice
  - SpeedLoaderSpecialPractice
  - MagazineBoxSpecial
  - MagazineBoxSpecialPractice
  - LPPC4Low
  # LP Edit End

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:
  - Flash
  - Stunbaton
  - CombatKnife
  - RiotShield
  # LP Edit Start
  - LPPWeaponRifleM14
  - LPPWeaponPF20kit
  - LPPWeaponSniperScout
  # LP Edit End

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield
  - ClothingBackpackHarmpack

- type: latheRecipePack
  id: SecurityBoards
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  - CableDetStack1
  - EmptyDetonator
  - ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
  - BoxBeanbag
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  - BoxShellTranquilizer
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxLightRifleUranium
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleUranium
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazineRifleIncendiary
  - MagazineRifleUranium
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium
#LP edit start
  - LPPMagazinePistolPF20Incendiary
  - MagazineBoxSpecialIncendiary
  - MagazineBoxSpecialUranium
  - MagazineBoxSpecialRubber
  - SpeedLoaderSpecialRubber
  - MagazinePistolSpecialRubber
  - SpeedLoaderSpecialUranium
  - LPPMagazinePistolPF20Uranium
#LP edit end

- type: latheRecipePack
  id: SecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon
  - WeaponTemperatureGun
  # LP Edit Start
  - LPPWeaponEnergyGunPistolDominator
  - LPPWeaponRiflepadefame
  - WeaponStarflareSMG
  - PowerCellStarflarePrinted
  - WeaponEnergyGun
  - WeaponEnergyGunPistol
  - WeaponGunLaserCarbineAutomatic
  # LP Edit End

- type: latheRecipePack
  id: SecurityDisablers
  recipes:
  - WeaponDisabler
  - WeaponDisablerSMG
  # LP Edit Start
  - WeaponPocketDisabler
  - WeaponStunProjector
  - WeaponAutoDisabler
  - WeaponDisablerCarbine
  - WeaponDisablerShotgun
  # LP Edit End
